-- CreateTable
CREATE TABLE "PO" (
    "PO_ID" SERIAL NOT NULL,
    "PO_RLSE_NBR" VARCHAR(50),
    "PO_RCVD_BY" VARCHAR(25),
    "VENDR_NM" VARCHAR(50),
    "USER_RQST_VIA_PURCH_FLG" BOOLEAN NOT NULL DEFAULT false,
    "PO_BU_NBR" VARCHAR(25),
    "E_RQSTN_NBR" VARCHAR(25),
    "PO_STATUS" VARCHAR(20),
    "PO_START_DT" DATE,
    "PO_EXPIR_DT" DATE,
    "TXDOT_GPS" BOOLEAN NOT NULL DEFAULT false,
    "MNTH_EQ_RATE" DECIMAL(10,2),
    "PO_TYPE" VARCHAR(50),
    "SPCL_EVNT" VARCHAR(100),
    "LAST_UPDT_BY" VARCHAR(50),
    "LAST_UPDT_DT" TIMESTAMP(3),
    "CHART_FIELDS_FLG" BOOLEAN NOT NULL DEFAULT false,
    "VENDOR_MAIL" VARCHAR(55),
    "VENDOR_PHN_NBR" VARCHAR(20),

    CONSTRAINT "PO_pkey" PRIMARY KEY ("PO_ID")
);

-- CreateTable
CREATE TABLE "RENTAL_PO" (
    "RENTAL_PO_ID" SERIAL NOT NULL,
    "RENTAL_ID" INTEGER NOT NULL,
    "PO_ID" INTEGER NOT NULL,

    CONSTRAINT "RENTAL_PO_pkey" PRIMARY KEY ("RENTAL_PO_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "RENTAL_PO_RENTAL_ID_PO_ID_key" ON "RENTAL_PO"("RENTAL_ID", "PO_ID");

-- AddForeignKey
ALTER TABLE "RENTAL_PO" ADD CONSTRAINT "RENTAL_PO_RENTAL_ID_fkey" FOREIGN KEY ("RENTAL_ID") REFERENCES "RENTAL"("RENTAL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RENTAL_PO" ADD CONSTRAINT "RENTAL_PO_PO_ID_fkey" FOREIGN KEY ("PO_ID") REFERENCES "PO"("PO_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
