-- CreateTable
CREATE TABLE "RENTAL_STATUS_HISTORY" (
    "HIST_ID" SERIAL NOT NULL,
    "RENTAL_ID" INTEGER NOT NULL,
    "STATUS" VARCHAR(50) NOT NULL,
    "ACTOR_ID" VARCHAR(50),
    "ACTOR_NM" VARCHAR(50),
    "NOTE" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RENTAL_STATUS_HISTORY_pkey" PRIMARY KEY ("HIST_ID")
);

-- AddForeignKey
ALTER TABLE "RENTAL_STATUS_HISTORY" ADD CONSTRAINT "RENTAL_STATUS_HISTORY_RENTAL_ID_fkey" FOREIGN KEY ("RENTAL_ID") REFERENCES "RENTAL"("RENTAL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
