-- CreateTable
CREATE TABLE "RENTAL_ATTACHMENT" (
    "ATTACHMENT_ID" SERIAL NOT NULL,
    "RENTAL_ID" INTEGER NOT NULL,
    "FILE_NAME" VARCHAR(255) NOT NULL,
    "FILE_SIZE" INTEGER NOT NULL,
    "FILE_MIME_TYPE" VARCHAR(100) NOT NULL,
    "FILE_URL" VARCHAR(500) NOT NULL,
    "UPLOADED_BY" VARCHAR(50),
    "UPLOADED_BY_NAME" VARCHAR(100),
    "UPLOADED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RENTAL_ATTACHMENT_pkey" PRIMARY KEY ("ATTACHMENT_ID")
);

-- AddForeignKey
ALTER TABLE "RENTAL_ATTACHMENT" ADD CONSTRAINT "RENTAL_ATTACHMENT_RENTAL_ID_fkey" FOREIGN KEY ("RENTAL_ID") REFERENCES "RENTAL"("RENTAL_ID") ON DELETE CASCADE ON UPDATE CASCADE;
