-- CreateTable
CREATE TABLE "DIST" (
    "DIST_NBR" INTEGER NOT NULL,
    "DIST_NM" VARCHAR(50) NOT NULL,
    "DIST_ABRVN" VARCHAR(3),
    "FIN_AREA" VARCHAR(50),
    "FIN_AREA_BSNES_NBR" VARCHAR(50),
    "RENT_COORD_DIST_CD_NBR" VARCHAR(50),

    CONSTRAINT "DIST_pkey" PRIMARY KEY ("DIST_NBR")
);

-- CreateTable
CREATE TABLE "SECTION" (
    "SECT_ID" SERIAL NOT NULL,
    "DIST_NBR" INTEGER NOT NULL,
    "SECT_NBR" VARCHAR(15),
    "SECT_NM" VARCHAR(100),

    CONSTRAINT "SECTION_pkey" PRIMARY KEY ("SECT_ID")
);

-- CreateTable
CREATE TABLE "NIGP" (
    "NIGP_CD" VARCHAR(30) NOT NULL,
    "CTGRY_ID" INTEGER,
    "FNAV_CAT" VARCHAR(13),
    "DSCR" VARCHAR(125),
    "AVG_MONTHLY_RATE" DECIMAL(10,2),

    CONSTRAINT "NIGP_pkey" PRIMARY KEY ("NIGP_CD")
);

-- CreateTable
CREATE TABLE "USERS" (
    "USR_ID" VARCHAR(18) NOT NULL,
    "USR_ROLE" VARCHAR(50) NOT NULL,
    "FIRST_NM" VARCHAR(30) NOT NULL,
    "LAST_NM" VARCHAR(30) NOT NULL,
    "USR_EMAIL" VARCHAR(50),
    "LAST_UPDT_DT" TIMESTAMP(3),
    "LAST_UPDT_BY" VARCHAR(20),
    "password" VARCHAR(255) NOT NULL,

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("USR_ID")
);

-- CreateTable
CREATE TABLE "RENTAL" (
    "RENTAL_ID" SERIAL NOT NULL,
    "SECT_ID" INTEGER NOT NULL,
    "DIST_NBR" INTEGER NOT NULL,
    "NIGP_CD" VARCHAR(30),
    "RENT_STATUS" VARCHAR(50),
    "SUBMIT_DT" DATE,
    "DLVRY_RQST_DT" DATE,
    "DLVRY_DT" DATE,
    "DLVRY_TIME" VARCHAR(10),
    "CALL_OFF_DT" DATE,
    "RENTAL_DUE_DT" DATE,
    "RQST_BY" VARCHAR(50),
    "DUR_LNGTH" INTEGER,
    "DUR_UOM" VARCHAR(50),
    "EQPMT_MODEL" VARCHAR(50),
    "EQPMT_MAKE" VARCHAR(100),
    "EQPMT_CMNT" TEXT,
    "EQPMT_ATCHMT" VARCHAR(200),
    "EQPMT_Qty" INTEGER,
    "EQPMT_Qty1" INTEGER,
    "EQPMT_Qty2" INTEGER,
    "DLVRY_LOCN" VARCHAR(1000),
    "POC_NM" VARCHAR(50),
    "POC_PHN_NBR" VARCHAR(15),
    "POC_SCNDRY_NM" VARCHAR(50),
    "POC_SCNDRY_PHN_NBR" VARCHAR(15),
    "CF_DEPT_NBR" VARCHAR(10),
    "CF_ACCT_NBR" VARCHAR(10),
    "CF_APPROP_YR" VARCHAR(10),
    "CF_APPROP_CLASS" VARCHAR(10),
    "CF_FUND" VARCHAR(10),
    "CF_BUS_UNIT" VARCHAR(10),
    "CF_PROJ" VARCHAR(20),
    "CF_ACTV" VARCHAR(10),
    "CF_SRC_TYPE" VARCHAR(10),
    "CF_TASK" VARCHAR(25),
    "SPCL_INST" VARCHAR(5000),
    "RENT_CMNT" TEXT,
    "SERVICE_CALL_CMNT" TEXT,
    "RCVD_BY" VARCHAR(50),
    "PO_PROCESSOR_NM" VARCHAR(50),
    "PO_PROCESSOR_PHN_NBR" VARCHAR(15),
    "TROUBLE_RENT_FLG" BOOLEAN NOT NULL DEFAULT false,
    "SERVICE_CALL_FLG" BOOLEAN,
    "USER_REQUEST_FLG" BOOLEAN,
    "VENDR_UNIT_NBR" TEXT,
    "REASON_CODES" VARCHAR(50),
    "ON_RENT_HRS" DECIMAL(10,2),
    "OFF_RENT_HRS" DECIMAL(10,2),
    "LAST_UPDT_BY" VARCHAR(50),
    "LAST_UPDT_DT" TIMESTAMP(3),

    CONSTRAINT "RENTAL_pkey" PRIMARY KEY ("RENTAL_ID")
);

-- AddForeignKey
ALTER TABLE "SECTION" ADD CONSTRAINT "SECTION_DIST_NBR_fkey" FOREIGN KEY ("DIST_NBR") REFERENCES "DIST"("DIST_NBR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RENTAL" ADD CONSTRAINT "RENTAL_SECT_ID_fkey" FOREIGN KEY ("SECT_ID") REFERENCES "SECTION"("SECT_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RENTAL" ADD CONSTRAINT "RENTAL_DIST_NBR_fkey" FOREIGN KEY ("DIST_NBR") REFERENCES "DIST"("DIST_NBR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RENTAL" ADD CONSTRAINT "RENTAL_NIGP_CD_fkey" FOREIGN KEY ("NIGP_CD") REFERENCES "NIGP"("NIGP_CD") ON DELETE SET NULL ON UPDATE CASCADE;
