-- CreateTable
CREATE TABLE "INVC" (
    "INVC_ID" SERIAL NOT NULL,
    "PO_ID" INTEGER,
    "RENTAL_ID" INTEGER,
    "INVC_NBR" VARCHAR(50),
    "INVC_DT" DATE,
    "INV_LINE_TOTAL" DECIMAL(10,2),
    "LAST_UPDT_BY" VARCHAR(50),
    "LAST_UPDT_DT" TIMESTAMP(3),

    CONSTRAINT "INVC_pkey" PRIMARY KEY ("INVC_ID")
);

-- CreateTable
CREATE TABLE "INVC_LN" (
    "INVC_LN_ID" SERIAL NOT NULL,
    "INVC_ID" INTEGER NOT NULL,
    "INVC_LN_NBR" INTEGER,
    "INVC_LN_AMT" DECIMAL(10,2),
    "INVC_LN_QTY" DECIMAL(10,2),
    "INVC_LN_UOM" VARCHAR(20),
    "INVC_LN_DSCR" VARCHAR(500),
    "LAST_UPDT_BY" VARCHAR(50),
    "LAST_UPDT_DT" TIMESTAMP(3),

    CONSTRAINT "INVC_LN_pkey" PRIMARY KEY ("INVC_LN_ID")
);

-- CreateTable
CREATE TABLE "CLAIM" (
    "CLAIM_ID" SERIAL NOT NULL,
    "INVC_ID" INTEGER,
    "CLAIM_NBR" VARCHAR(50),
    "CLAIM_DT" DATE,
    "CLAIM_AMT" DECIMAL(10,2),
    "CLAIM_STATUS" VARCHAR(50),
    "CLAIM_TYPE" VARCHAR(50),
    "LAST_UPDT_BY" VARCHAR(50),
    "LAST_UPDT_DT" TIMESTAMP(3),

    CONSTRAINT "CLAIM_pkey" PRIMARY KEY ("CLAIM_ID")
);

-- AddForeignKey
ALTER TABLE "INVC" ADD CONSTRAINT "INVC_PO_ID_fkey" FOREIGN KEY ("PO_ID") REFERENCES "PO"("PO_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVC_LN" ADD CONSTRAINT "INVC_LN_INVC_ID_fkey" FOREIGN KEY ("INVC_ID") REFERENCES "INVC"("INVC_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLAIM" ADD CONSTRAINT "CLAIM_INVC_ID_fkey" FOREIGN KEY ("INVC_ID") REFERENCES "INVC"("INVC_ID") ON DELETE SET NULL ON UPDATE CASCADE;
