-- AlterTable
ALTER TABLE "USERS" ADD COLUMN     "DIST_NBR" INTEGER,
ADD COLUMN     "SECT_ID" INTEGER,
ADD COLUMN     "USR_PHN_NBR" VARCHAR(20);

-- AddForeignKey
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_DIST_NBR_fkey" FOREIGN KEY ("DIST_NBR") REFERENCES "DIST"("DIST_NBR") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_SECT_ID_fkey" FOREIGN KEY ("SECT_ID") REFERENCES "SECTION"("SECT_ID") ON DELETE SET NULL ON UPDATE CASCADE;
